version: '3.8'

services:
  catalogdb:
    image: mongo

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4    

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}disountapi
    build:
      context: .
      dockerfile: Services/Disount/Disount.API/Dockerfile

  rabitmq:
    image: rabbitmq:3-management-alpine
  
  rediscache:
    image: redis
  
  portainer:
    image: portainer/portainer-ce
 
  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    

  discount.gprc:
    image: ${DOCKER_REGISTRY-}discountgprc
    build:
      context: .
      dockerfile: Services/Disount/Discount.Gprc/Dockerfile

  shortenurl:
    image: ${DOCKER_REGISTRY-}shortenurl
    build:
      context: .
      dockerfile: Services/ShortenURL/ShortenUrl/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  orderdb_data:
  postgres_data:
  pgadmin_data:

