version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=ramzi@bdair.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - "5050:80" 
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis:ConnectionString:rediscache:6379"
      - "DiscountGprcServerSetting:Address:http://discount.gprc"
    depends_on:
      - rediscache
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Database:ConnectionString:Server=discountdb;Port=5432;Database=admin;User Id =admin;Password=admin"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  discount.gprc:
    container_name: discount.gprc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Database:ConnectionString:Server=localhost;Port=5432;Database=admin;User Id =admin;Password=admin"
    depends_on:
      - discountdb
    ports:
      - "8003:80"


  rabitmq:
    container_name: rabiitmq
    restart: always
    ports:
      - 5672:5672

  rediscache:
    container_name: rediscache
    restart: always
    ports:
      - 6379:6379
      - 15672:15672

  portainer:
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  orderdb:
    container_name: orderdb
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - orderdb_data:/var/opt/mssql 
 
      


