version: '3.4'

services:
  catalogdb:
    image: mongo
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  rabitmq:
    image: rabbitmq:3-management-alpine
  
  rediscache:
    image: redis
  
  portainer:
    image: portainer/portainer-ce

volumes:
  mongo_data:
  portainer_data:

